name: muts
description: Mutual Support

version: 1.0.0+1

module:
  androidX: true
  
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^0.5.0+1
  photo_view: ^0.5.0
  flutter_icons: ^1.1.0
  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.13.5
  get_it: ^1.0.3+2
  fluttertoast: ^3.1.3
  flutter_lock_screen: '^1.0.5'
  fluttericon: ^1.0.3
  cached_network_image: 2.0.0-rc.1
  shared_preferences: ^0.5.3+4
  firebase_messaging: 6.0.13
  flutter_local_notifications: 1.4.0
  intl: ^0.15.7
  flutter_auth_buttons: ^0.8.0
  image_picker: ^0.6.6+1
  path_provider: ^1.6.7
  google_sign_in: ^4.0.7
  firebase_storage: ^3.1.5
  line_awesome_icons: ^1.0.4+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true